name: Update Binary Version

on:
  repository_dispatch:
    types: [update_binary_version]

permissions:
  contents: write

jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update Package.swift
        run: |
          ASSET_URL="https://github.com/p-x9/MachOKit/releases/download/${{ github.event.client_payload.version }}/MachOKit.xcframework.zip"
          CHECKSUM="${{ github.event.client_payload.mach-o_kit_checksum }}"
          TARGET_NAME="MachOKitBin"
          perl -0777 -i -s -pe '
            s{
              (
                \.binaryTarget\s*\(\s*
                name:\s*"\Q$target\E"\s*,\s*
                url:\s*"
              )
              [^"]+
              (
                "\s*,\s*checksum:\s*"
              )
              [^"]+
              (
                "\s*\)
              )
            }{$1$url$2$checksum$3}xsg;
          ' -- -target="$TARGET_NAME" -url="$ASSET_URL" -checksum="$CHECKSUM" Package.swift

          ASSET_URL="https://github.com/p-x9/MachOKit/releases/download/${{ github.event.client_payload.version }}/MachOKitC.xcframework.zip"
          CHECKSUM="${{ github.event.client_payload.mach-o_kit_c_checksum }}"
          TARGET_NAME="MachOKitCBin"
          perl -0777 -i -s -pe '
            s{
              (
                \.binaryTarget\s*\(\s*
                name:\s*"\Q$target\E"\s*,\s*
                url:\s*"
              )
              [^"]+
              (
                "\s*,\s*checksum:\s*"
              )
              [^"]+
              (
                "\s*\)
              )
            }{$1$url$2$checksum$3}xsg;
          ' -- -target="$TARGET_NAME" -url="$ASSET_URL" -checksum="$CHECKSUM" Package.swift

      - name: Commit & Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Package.swift
          git commit -m "version ${{ github.event.client_payload.version }}"
          git tag "${{ github.event.client_payload.version }}"
          git push origin main
          git push origin "${{ github.event.client_payload.version }}"

      - name: Release
        run: |
          gh release create "${{ github.event.client_payload.version }}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
